// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.17.3
// source: tariff.proto

package tariff

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TariffType int32

const (
	TariffType_FIXED   TariffType = 0
	TariffType_PERCENT TariffType = 1
)

// Enum value maps for TariffType.
var (
	TariffType_name = map[int32]string{
		0: "FIXED",
		1: "PERCENT",
	}
	TariffType_value = map[string]int32{
		"FIXED":   0,
		"PERCENT": 1,
	}
)

func (x TariffType) Enum() *TariffType {
	p := new(TariffType)
	*p = x
	return p
}

func (x TariffType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TariffType) Descriptor() protoreflect.EnumDescriptor {
	return file_tariff_proto_enumTypes[0].Descriptor()
}

func (TariffType) Type() protoreflect.EnumType {
	return &file_tariff_proto_enumTypes[0]
}

func (x TariffType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TariffType.Descriptor instead.
func (TariffType) EnumDescriptor() ([]byte, []int) {
	return file_tariff_proto_rawDescGZIP(), []int{0}
}

type Tariff struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string     `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          TariffType `protobuf:"varint,3,opt,name=type,proto3,enum=tariff.TariffType" json:"type,omitempty"`
	AmountForCash float64    `protobuf:"fixed64,4,opt,name=amount_for_cash,json=amountForCash,proto3" json:"amount_for_cash,omitempty"`
	AmountForCard float64    `protobuf:"fixed64,5,opt,name=amount_for_card,json=amountForCard,proto3" json:"amount_for_card,omitempty"`
}

func (x *Tariff) Reset() {
	*x = Tariff{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tariff_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Tariff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tariff) ProtoMessage() {}

func (x *Tariff) ProtoReflect() protoreflect.Message {
	mi := &file_tariff_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tariff.ProtoReflect.Descriptor instead.
func (*Tariff) Descriptor() ([]byte, []int) {
	return file_tariff_proto_rawDescGZIP(), []int{0}
}

func (x *Tariff) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Tariff) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tariff) GetType() TariffType {
	if x != nil {
		return x.Type
	}
	return TariffType_FIXED
}

func (x *Tariff) GetAmountForCash() float64 {
	if x != nil {
		return x.AmountForCash
	}
	return 0
}

func (x *Tariff) GetAmountForCard() float64 {
	if x != nil {
		return x.AmountForCard
	}
	return 0
}

type CreateTariffRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name          string     `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          TariffType `protobuf:"varint,2,opt,name=type,proto3,enum=tariff.TariffType" json:"type,omitempty"`
	AmountForCash float64    `protobuf:"fixed64,3,opt,name=amount_for_cash,json=amountForCash,proto3" json:"amount_for_cash,omitempty"`
	AmountForCard float64    `protobuf:"fixed64,4,opt,name=amount_for_card,json=amountForCard,proto3" json:"amount_for_card,omitempty"`
}

func (x *CreateTariffRequest) Reset() {
	*x = CreateTariffRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tariff_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTariffRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTariffRequest) ProtoMessage() {}

func (x *CreateTariffRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tariff_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTariffRequest.ProtoReflect.Descriptor instead.
func (*CreateTariffRequest) Descriptor() ([]byte, []int) {
	return file_tariff_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTariffRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTariffRequest) GetType() TariffType {
	if x != nil {
		return x.Type
	}
	return TariffType_FIXED
}

func (x *CreateTariffRequest) GetAmountForCash() float64 {
	if x != nil {
		return x.AmountForCash
	}
	return 0
}

func (x *CreateTariffRequest) GetAmountForCard() float64 {
	if x != nil {
		return x.AmountForCard
	}
	return 0
}

type CreateTariffResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tariff *Tariff `protobuf:"bytes,1,opt,name=tariff,proto3" json:"tariff,omitempty"`
}

func (x *CreateTariffResponse) Reset() {
	*x = CreateTariffResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tariff_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTariffResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTariffResponse) ProtoMessage() {}

func (x *CreateTariffResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tariff_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTariffResponse.ProtoReflect.Descriptor instead.
func (*CreateTariffResponse) Descriptor() ([]byte, []int) {
	return file_tariff_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTariffResponse) GetTariff() *Tariff {
	if x != nil {
		return x.Tariff
	}
	return nil
}

type IdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *IdRequest) Reset() {
	*x = IdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tariff_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdRequest) ProtoMessage() {}

func (x *IdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tariff_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdRequest.ProtoReflect.Descriptor instead.
func (*IdRequest) Descriptor() ([]byte, []int) {
	return file_tariff_proto_rawDescGZIP(), []int{3}
}

func (x *IdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetTariffResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tariff *Tariff `protobuf:"bytes,1,opt,name=tariff,proto3" json:"tariff,omitempty"`
}

func (x *GetTariffResponse) Reset() {
	*x = GetTariffResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tariff_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTariffResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTariffResponse) ProtoMessage() {}

func (x *GetTariffResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tariff_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTariffResponse.ProtoReflect.Descriptor instead.
func (*GetTariffResponse) Descriptor() ([]byte, []int) {
	return file_tariff_proto_rawDescGZIP(), []int{4}
}

func (x *GetTariffResponse) GetTariff() *Tariff {
	if x != nil {
		return x.Tariff
	}
	return nil
}

type UpdateTariffRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string     `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          TariffType `protobuf:"varint,3,opt,name=type,proto3,enum=tariff.TariffType" json:"type,omitempty"`
	AmountForCash float64    `protobuf:"fixed64,4,opt,name=amount_for_cash,json=amountForCash,proto3" json:"amount_for_cash,omitempty"`
	AmountForCard float64    `protobuf:"fixed64,5,opt,name=amount_for_card,json=amountForCard,proto3" json:"amount_for_card,omitempty"`
}

func (x *UpdateTariffRequest) Reset() {
	*x = UpdateTariffRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tariff_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateTariffRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTariffRequest) ProtoMessage() {}

func (x *UpdateTariffRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tariff_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTariffRequest.ProtoReflect.Descriptor instead.
func (*UpdateTariffRequest) Descriptor() ([]byte, []int) {
	return file_tariff_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateTariffRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateTariffRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateTariffRequest) GetType() TariffType {
	if x != nil {
		return x.Type
	}
	return TariffType_FIXED
}

func (x *UpdateTariffRequest) GetAmountForCash() float64 {
	if x != nil {
		return x.AmountForCash
	}
	return 0
}

func (x *UpdateTariffRequest) GetAmountForCard() float64 {
	if x != nil {
		return x.AmountForCard
	}
	return 0
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tariff_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_tariff_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_tariff_proto_rawDescGZIP(), []int{6}
}

func (x *Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListTariffsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Limit int32 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *ListTariffsRequest) Reset() {
	*x = ListTariffsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tariff_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListTariffsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTariffsRequest) ProtoMessage() {}

func (x *ListTariffsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tariff_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTariffsRequest.ProtoReflect.Descriptor instead.
func (*ListTariffsRequest) Descriptor() ([]byte, []int) {
	return file_tariff_proto_rawDescGZIP(), []int{7}
}

func (x *ListTariffsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListTariffsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tariffs []*Tariff `protobuf:"bytes,1,rep,name=tariffs,proto3" json:"tariffs,omitempty"`
	Count   int32     `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *ListTariffsResponse) Reset() {
	*x = ListTariffsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tariff_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListTariffsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTariffsResponse) ProtoMessage() {}

func (x *ListTariffsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tariff_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTariffsResponse.ProtoReflect.Descriptor instead.
func (*ListTariffsResponse) Descriptor() ([]byte, []int) {
	return file_tariff_proto_rawDescGZIP(), []int{8}
}

func (x *ListTariffsResponse) GetTariffs() []*Tariff {
	if x != nil {
		return x.Tariffs
	}
	return nil
}

func (x *ListTariffsResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_tariff_proto protoreflect.FileDescriptor

var file_tariff_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x74, 0x61, 0x72, 0x69, 0x66, 0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x74, 0x61, 0x72, 0x69, 0x66, 0x66, 0x22, 0xa4, 0x01, 0x0a, 0x06, 0x54, 0x61, 0x72, 0x69, 0x66,
	0x66, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x26, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x74, 0x61, 0x72, 0x69, 0x66, 0x66, 0x2e, 0x54, 0x61, 0x72,
	0x69, 0x66, 0x66, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x26, 0x0a,
	0x0f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x66, 0x6f, 0x72, 0x5f, 0x63, 0x61, 0x73, 0x68,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0d, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x46, 0x6f,
	0x72, 0x43, 0x61, 0x73, 0x68, 0x12, 0x26, 0x0a, 0x0f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x5f,
	0x66, 0x6f, 0x72, 0x5f, 0x63, 0x61, 0x72, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0d,
	0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x46, 0x6f, 0x72, 0x43, 0x61, 0x72, 0x64, 0x22, 0xa1, 0x01,
	0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x61, 0x72, 0x69, 0x66, 0x66, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x26, 0x0a, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x74, 0x61, 0x72, 0x69, 0x66, 0x66,
	0x2e, 0x54, 0x61, 0x72, 0x69, 0x66, 0x66, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x12, 0x26, 0x0a, 0x0f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x66, 0x6f, 0x72, 0x5f,
	0x63, 0x61, 0x73, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0d, 0x61, 0x6d, 0x6f, 0x75,
	0x6e, 0x74, 0x46, 0x6f, 0x72, 0x43, 0x61, 0x73, 0x68, 0x12, 0x26, 0x0a, 0x0f, 0x61, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x5f, 0x66, 0x6f, 0x72, 0x5f, 0x63, 0x61, 0x72, 0x64, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x0d, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x46, 0x6f, 0x72, 0x43, 0x61, 0x72,
	0x64, 0x22, 0x3e, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x61, 0x72, 0x69, 0x66,
	0x66, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x06, 0x74, 0x61, 0x72,
	0x69, 0x66, 0x66, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x74, 0x61, 0x72, 0x69,
	0x66, 0x66, 0x2e, 0x54, 0x61, 0x72, 0x69, 0x66, 0x66, 0x52, 0x06, 0x74, 0x61, 0x72, 0x69, 0x66,
	0x66, 0x22, 0x1b, 0x0a, 0x09, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x3b,
	0x0a, 0x11, 0x47, 0x65, 0x74, 0x54, 0x61, 0x72, 0x69, 0x66, 0x66, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x06, 0x74, 0x61, 0x72, 0x69, 0x66, 0x66, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x74, 0x61, 0x72, 0x69, 0x66, 0x66, 0x2e, 0x54, 0x61, 0x72,
	0x69, 0x66, 0x66, 0x52, 0x06, 0x74, 0x61, 0x72, 0x69, 0x66, 0x66, 0x22, 0xb1, 0x01, 0x0a, 0x13,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x61, 0x72, 0x69, 0x66, 0x66, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x26, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x74, 0x61, 0x72, 0x69, 0x66, 0x66, 0x2e, 0x54,
	0x61, 0x72, 0x69, 0x66, 0x66, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12,
	0x26, 0x0a, 0x0f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x66, 0x6f, 0x72, 0x5f, 0x63, 0x61,
	0x73, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0d, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74,
	0x46, 0x6f, 0x72, 0x43, 0x61, 0x73, 0x68, 0x12, 0x26, 0x0a, 0x0f, 0x61, 0x6d, 0x6f, 0x75, 0x6e,
	0x74, 0x5f, 0x66, 0x6f, 0x72, 0x5f, 0x63, 0x61, 0x72, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x0d, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x46, 0x6f, 0x72, 0x43, 0x61, 0x72, 0x64, 0x22,
	0x24, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x2a, 0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x61, 0x72,
	0x69, 0x66, 0x66, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c,
	0x69, 0x6d, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69,
	0x74, 0x22, 0x55, 0x0a, 0x13, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x61, 0x72, 0x69, 0x66, 0x66, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x07, 0x74, 0x61, 0x72, 0x69,
	0x66, 0x66, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x74, 0x61, 0x72, 0x69,
	0x66, 0x66, 0x2e, 0x54, 0x61, 0x72, 0x69, 0x66, 0x66, 0x52, 0x07, 0x74, 0x61, 0x72, 0x69, 0x66,
	0x66, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2a, 0x24, 0x0a, 0x0a, 0x54, 0x61, 0x72, 0x69,
	0x66, 0x66, 0x54, 0x79, 0x70, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x46, 0x49, 0x58, 0x45, 0x44, 0x10,
	0x00, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x45, 0x52, 0x43, 0x45, 0x4e, 0x54, 0x10, 0x01, 0x32, 0xbc,
	0x02, 0x0a, 0x0d, 0x54, 0x61, 0x72, 0x69, 0x66, 0x66, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x45, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x1b, 0x2e, 0x74, 0x61, 0x72,
	0x69, 0x66, 0x66, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x61, 0x72, 0x69, 0x66, 0x66,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x74, 0x61, 0x72, 0x69, 0x66, 0x66,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x61, 0x72, 0x69, 0x66, 0x66, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x35, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x11,
	0x2e, 0x74, 0x61, 0x72, 0x69, 0x66, 0x66, 0x2e, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x19, 0x2e, 0x74, 0x61, 0x72, 0x69, 0x66, 0x66, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x61,
	0x72, 0x69, 0x66, 0x66, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x41,
	0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1a, 0x2e, 0x74, 0x61, 0x72, 0x69, 0x66, 0x66, 0x2e,
	0x4c, 0x69, 0x73, 0x74, 0x54, 0x61, 0x72, 0x69, 0x66, 0x66, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x74, 0x61, 0x72, 0x69, 0x66, 0x66, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x54, 0x61, 0x72, 0x69, 0x66, 0x66, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x39, 0x0a, 0x06, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x1b, 0x2e, 0x74, 0x61,
	0x72, 0x69, 0x66, 0x66, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x61, 0x72, 0x69, 0x66,
	0x66, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x74, 0x61, 0x72, 0x69, 0x66,
	0x66, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x2f, 0x0a, 0x06,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x11, 0x2e, 0x74, 0x61, 0x72, 0x69, 0x66, 0x66, 0x2e,
	0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x74, 0x61, 0x72, 0x69,
	0x66, 0x66, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x11, 0x5a,
	0x0f, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x61, 0x72, 0x69, 0x66, 0x66,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tariff_proto_rawDescOnce sync.Once
	file_tariff_proto_rawDescData = file_tariff_proto_rawDesc
)

func file_tariff_proto_rawDescGZIP() []byte {
	file_tariff_proto_rawDescOnce.Do(func() {
		file_tariff_proto_rawDescData = protoimpl.X.CompressGZIP(file_tariff_proto_rawDescData)
	})
	return file_tariff_proto_rawDescData
}

var file_tariff_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_tariff_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_tariff_proto_goTypes = []interface{}{
	(TariffType)(0),              // 0: tariff.TariffType
	(*Tariff)(nil),               // 1: tariff.Tariff
	(*CreateTariffRequest)(nil),  // 2: tariff.CreateTariffRequest
	(*CreateTariffResponse)(nil), // 3: tariff.CreateTariffResponse
	(*IdRequest)(nil),            // 4: tariff.IdRequest
	(*GetTariffResponse)(nil),    // 5: tariff.GetTariffResponse
	(*UpdateTariffRequest)(nil),  // 6: tariff.UpdateTariffRequest
	(*Response)(nil),             // 7: tariff.Response
	(*ListTariffsRequest)(nil),   // 8: tariff.ListTariffsRequest
	(*ListTariffsResponse)(nil),  // 9: tariff.ListTariffsResponse
}
var file_tariff_proto_depIdxs = []int32{
	0,  // 0: tariff.Tariff.type:type_name -> tariff.TariffType
	0,  // 1: tariff.CreateTariffRequest.type:type_name -> tariff.TariffType
	1,  // 2: tariff.CreateTariffResponse.tariff:type_name -> tariff.Tariff
	1,  // 3: tariff.GetTariffResponse.tariff:type_name -> tariff.Tariff
	0,  // 4: tariff.UpdateTariffRequest.type:type_name -> tariff.TariffType
	1,  // 5: tariff.ListTariffsResponse.tariffs:type_name -> tariff.Tariff
	2,  // 6: tariff.TariffService.Create:input_type -> tariff.CreateTariffRequest
	4,  // 7: tariff.TariffService.Get:input_type -> tariff.IdRequest
	8,  // 8: tariff.TariffService.List:input_type -> tariff.ListTariffsRequest
	6,  // 9: tariff.TariffService.Update:input_type -> tariff.UpdateTariffRequest
	4,  // 10: tariff.TariffService.Delete:input_type -> tariff.IdRequest
	3,  // 11: tariff.TariffService.Create:output_type -> tariff.CreateTariffResponse
	5,  // 12: tariff.TariffService.Get:output_type -> tariff.GetTariffResponse
	9,  // 13: tariff.TariffService.List:output_type -> tariff.ListTariffsResponse
	7,  // 14: tariff.TariffService.Update:output_type -> tariff.Response
	7,  // 15: tariff.TariffService.Delete:output_type -> tariff.Response
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_tariff_proto_init() }
func file_tariff_proto_init() {
	if File_tariff_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tariff_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Tariff); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tariff_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTariffRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tariff_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTariffResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tariff_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tariff_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTariffResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tariff_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateTariffRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tariff_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tariff_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListTariffsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tariff_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListTariffsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tariff_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tariff_proto_goTypes,
		DependencyIndexes: file_tariff_proto_depIdxs,
		EnumInfos:         file_tariff_proto_enumTypes,
		MessageInfos:      file_tariff_proto_msgTypes,
	}.Build()
	File_tariff_proto = out.File
	file_tariff_proto_rawDesc = nil
	file_tariff_proto_goTypes = nil
	file_tariff_proto_depIdxs = nil
}
